version: '3.8'

services:
  pg:
    container_name: social_scribe.postgres
    image: postgres:18 # Use a specific version for consistency, e.g., postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/18 # Persistent storage for database data
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: social_scribe.pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Access pgAdmin at http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres
    depends_on:
      - pg

networks:
  postgres:
    driver: bridge
volumes:
  postgres_data:
  pgadmin_data:
